{% set version = "0.1-6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-kmsurv
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/KMsurv_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/KMsurv/KMsurv_{{ version }}.tar.gz
  sha256: 42ec6f2a014b27277ada313ecf21994345704f8b719fe5e7bee8ad4f91652f32

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('KMsurv')"           # [not win]
    - "\"%R%\" -e \"library('KMsurv')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=KMsurv
  license: GPL-3.0-or-later
  summary: Data sets and functions for Klein and Moeschberger (1997), "Survival Analysis, Techniques for Censored and Truncated Data", Springer.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
