travis:
  secure:
    BINSTAR_TOKEN: sYrPoxtUxPYqe2GDIVraSIeJ2GhWEvMz15D2FBYjWnjTHSGCHuyJBVQYpJFKbKXk/W8M5fm25Oq5dr23om4pukA3VTszLofZWVjqHFgrWmc7SQYYpnZVy9KE8CtUaQ/a+orlgG5Cu0XUz/sBTZiq+Cv7yCPNfPIo+cHVpPzRZKqJjijV+wlzP6ukx7vCPYl3t1HR1rLeY5Pn5tdlTnJT2nRupBfHo05I21Goyi4MEDSVj3qNu3l2ot5CEKKLNai8SzKoDuU8FF3SOKXR1RolJtYgugvnCZCAmKkPXNpO8u7h+YvW6k5dQ3scPMYUSRTFBz9AwSZBulTL28QCdfMsU1oT+lxgqOcj26RXP7Xq51fk3vMZBKXXbd5nCWD7otqHfu7s44cg2FdfcGZd7wNLjIoDUrGIquKn5Y4mX8fkEajLP8LLLpFJwaZMqLEvj7spFtt3es2IHWqyynSb8jtz7VfgTpBW2/9f1X7SIXTZWRz8n3bR7vUFWXCYfUpiLHAi1ypKqET0XAgk2iB96OY/i+hFcdbYLRGd9o1bgQWI6XNr8hbzNFtq9KI3kWyVteutXny5U/aALpj6pzzRPTQIzuCLS/2vmEeLRU1+bW5pmgetvBD5wIoz4UYfazUWo6AyxgsgoqEglrshfEh7MCX/u7Dia+cKl8/VyYQF2d7HSys=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
