appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: MHT+yUcOeSZpoLAJXc93NDfaayhOkkqUWSClRKnJgrMlJYSH+1bzUbsLqd3fvDOtGvO2HFutKiFVX89MJjlaRcjLWzaw3+u4KT1yPrNQdv6auxyO/YHK7s7JI4+mTAI8OEmq6vxXz/pKwiUfyIEVn+VXorWZrfOJ5U5D0aT7U8nEUpK0KIAw8w2okCYtggNXXn17OXid8XO/n157u8u0SPDM78efTI96srU8d/cpss/xIcckPbOvL2Itc71jK3mifTO9tVHiT41jRJbE/vmb+vayPOVsZwVPh214rmT4XzvKRZzFsw82PgF9+5elF3KgO1rhlZcQbfkZC///tor3wwZKUsxXVrdAuqsOfP9esvKBCAsknr0ymm1MfMpFg51+g56gaiIHTx1ktronuNWc+3VnCSef3sl3cK83tyNu4MVg8VOLLPgu7Qp+1KoykyR0BHDrsNnwkt3v4vqd+Sjgi4Ubp6pB8KKJ3WwmNuPPBa9/L93ldbWeJ40Ic4KjO7zeK+LAKMOylPNj8d1y7I9+YbX6cZ7m8/5PY4MSCJestHd7UAWoJznuYKu+fgMqLi6Rg753Ymef8eait7CJcIJ5/fGWpWQKi+Q6m/noo5F7eDtN5I72XC3t9GPaA1/OiOqcbGpIqO585DbTK3CD5R7K5N/uVcT/2gdUjc8fMGSP/O0=
